from __future__ import annotations

import asyncio
import io
import traceback as tb

from abc import abstractmethod
from collections.abc import Iterable, Iterator
from contextlib import nullcontext
from functools import partial
from types import FunctionType
from typing import Any, Self, final

import panel as pn
import param

from panel.custom import JSComponent
from panel.io import hold
from panel.io.cache import is_equal
from panel.layout.base import (
    Column, ListLike, NamedListLike, Row,
)
from panel.pane import Markdown
from panel.viewable import Viewable, Viewer
from panel_material_ui import (
    Accordion, BreakpointSwitcher, Button, Card, ChatFeed, ChatMessage,
    Checkbox, Container, Dialog, Divider, FileDownload, IconButton, MenuButton,
    Progress, Select, SpeedDial, Tabs, TextAreaInput, TextInput, Typography,
)

from ..config import config
from ..pipeline import Pipeline
from ..views.base import Panel, View
from .actor import (
    Actor, ContextProvider, NullStep, TContext,
)
from .config import MissingContextError
from .context import (
    LWW, ContextError, ValidationIssue, collect_task_outputs,
    input_dependency_keys, merge_contexts, validate_task_inputs,
    validate_taskgroup_exclusions,
)
from .editors import LumenEditor
from .export import (
    format_output, make_md_cell, make_preamble, write_notebook,
)
from .llm import Llm, Message
from .tools import FunctionTool, Tool
from .utils import (
    content_to_text, extract_block_source, get_block_names, set_content_text,
    wrap_logfire_on_method,
)


def _export_checkbox(task, status_source, align="center"):
    """
    Checkbox controlling whether a task's outputs are kept when the report is
    exported. ``status_source`` supplies the status it tracks, so it only
    appears once that has something to export.
    """
    return Checkbox.from_param(
        task.param.include_in_export,
        label="",
        align=align,
        margin=(0, 4, 0, 0),
        # No description: it would render an info icon; the report explains the
        # checkboxes at the top instead.
        description="",
        visible=param.bind(
            lambda status, views: (
                status in ("success", "error", "cancelled") or bool(views)
            ),
            status_source.param.status, status_source.param.views,
        ),
    )


def _export_header(section, status_source, variant="h3"):
    """Heading for a section, with the checkbox that keeps or discards it."""
    title = Typography(section.param.title, variant=variant, margin=0)
    return Row(
        _export_checkbox(section, status_source), title,
        align="center", sizing_mode="stretch_width",
    )


class EditableProse(JSComponent):
    """
    A paragraph the user can edit in place, like a document editor.

    Typing syncs the text back to ``value``. ``value`` is only written back into
    the element when it differs from what is already there, because assigning to
    a contenteditable node resets the caret to the start, which would make it
    impossible to type.
    """

    value = param.String(default="", doc="""
        The edited text.""")

    _esm = """
    export function render({ model }) {
      const div = document.createElement('div')
      div.contentEditable = 'true'
      div.className = 'editable-prose'
      div.textContent = model.value
      div.addEventListener('input', () => { model.value = div.textContent })
      model.on('value', () => {
        if (div.textContent !== model.value) {
          div.textContent = model.value
        }
      })
      return div
    }
    """

    _stylesheets = [
        """
        .editable-prose {
          outline: none;
          padding: 4px 6px;
          border-radius: 4px;
          white-space: pre-wrap;
        }
        .editable-prose:hover { background: rgba(127, 127, 127, 0.08); }
        .editable-prose:focus { background: rgba(127, 127, 127, 0.12); }
        """
    ]


class Task(Viewer):
    """
    A `Task` defines a single unit of work that can be executed and rendered.
    """

    abort_on_error = param.Boolean(default=True, doc="""
        If True, the report will abort if an error occurs.""")

    context = param.Dict(default={}, allow_refs=True, doc="""
        The context to pass to the task.""")

    history = param.List(doc="""
        Conversation history to include as context for the task.""")

    include_in_export = param.Boolean(default=True, doc="""
        Whether this task's outputs are included when the report is exported.""")

    instruction = param.String(default="", doc="""
        The instruction to give to the task.""")

    interface = param.ClassSelector(class_=ChatFeed, doc="""
        The chat interface to use for the task.""")

    llm = param.ClassSelector(class_=Llm, doc="""
        The LLM to use for the task.""")

    out_context = param.Dict(default={}, doc="""
        The context generated by the task.""")

    parent = param.Parameter(doc="""
        The parent task group.""")

    running = param.Boolean(doc="""
        Whether the task is currently running.""")

    status = param.Selector(objects=["idle", "running", "success", "error", "cancelled"], default="idle", doc="""
        The current status of the task.""")

    steps_layout = param.ClassSelector(default=None, class_=(ListLike, NamedListLike), allow_None=True, doc="""
        The layout progress updates will be streamed to.""")

    title = param.String(doc="""
        The title of the task.""")

    views = param.List(allow_refs=True, doc="""
        The generated viewable outputs of the task.""")

    _header = param.List()

    def __init_subclass__(cls, **kwargs):
        """
        Apply wrap_logfire to all the subclasses' execute automatically
        """
        super().__init_subclass__(**kwargs)
        wrap_logfire_on_method(cls, "execute")

    def __init__(self, **params):
        super().__init__(**params)
        self._prepared = False
        self._init_view()
        self._null_step = NullStep()
        self._title = Typography(f"{'#'*self.level} {self.title}", margin=(10, 10, 0, 10))

    @param.depends("title", watch=True)
    def _update_title(self):
        self._title = f"{'#'*self.level} {self.title}"

    def __repr__(self):
        params = []
        if self.instruction:
            params.append(f"instruction='{self.instruction}'")
        if self.title:
            params.append(f"title='{self.title}'")
        return f"{self.__class__.__name__}({', '.join(params)})"

    def _init_view(self):
        self._view = self._container = Column(
            sizing_mode='stretch_width', styles={'min-height': 'unset'}, height_policy='fit'
        )

    def _add_step(self, title: str = "", **kwargs):
        """Private contextmanager for adding steps to the interface.

        If self.interface is None, returns a nullcontext that captures calls.
        Otherwise, returns the interface's add_step contextmanager.
        """
        if self.steps_layout is not None and 'steps_layout' not in kwargs:
            kwargs['steps_layout'] = self.steps_layout
        return nullcontext(self._null_step) if self.interface is None else self.interface.add_step(title=title, **kwargs)

    def _populate_view(self):
        self._view[:] = self._header

    def _render_controls(self):
        return [
            TextInput.from_param(
                self.param.title, sizing_mode="stretch_width", margin=(10, 0)
            ),
            TextAreaInput.from_param(
                self.param.instruction, sizing_mode="stretch_width", margin=(10, 0)
            ),
        ]

    def _render_message_history(self, context: TContext) -> list[Message]:
        messages = list(self.history)
        if not self.instruction or any(self.instruction in content_to_text(msg.get("content")) for msg in messages):
            return messages

        # Find the last user message
        last_user_idx = None
        for i in range(len(messages) - 1, -1, -1):
            if messages[i].get("role") == "user":
                last_user_idx = i
                break

        if last_user_idx is None:
            return [*messages, {"role": "user", "content": self.instruction}]

        user_msg = messages[last_user_idx]
        content = user_msg.get("content")
        text_content = content_to_text(content)
        updated_text = f"{text_content}\n\nInstruction: {self.instruction}"
        updated_msg = {
            **user_msg,
            "content": set_content_text(updated_text, content),
        }
        return [*messages[:last_user_idx], updated_msg, *messages[last_user_idx + 1:]]

    def _render_output(self, out):
        if isinstance(out, str):
            return Typography(out, margin=(20, 10))
        elif isinstance(out, ChatMessage):
            obj = out.object
            if isinstance(obj, str):
                return Typography(obj, margin=(20, 10))
            return obj
        elif isinstance(out, (Viewable, View, LumenEditor)):
            return out

    def __panel__(self):
        return self._container

    @abstractmethod
    async def _execute(self, context: TContext, **kwargs) -> tuple[list[Any], TContext]:
        raise NotImplementedError(f"{self.__class__.__name__} does not implement the execute.")

    def cleanup(self):
        """
        Cleanup when the task is not longer needed.

        Distinct from reset which only resets the outputs.
        """
        self.reset()

    def editor(self, show_title: bool = True) -> Viewable:
        """
        Returns the editor for the task.

        Arguments
        ----------
        show_title: bool
            Whether to show the title of the task.

        Returns
        -------
        The editor for the task.
        """
        return Column(*self._render_controls())

    async def execute(self, context: TContext | None = None, **kwargs) -> tuple[list[Any], TContext]:
        """
        Executes the task.

        Arguments
        ----------
        **kwargs: dict
            Additional keyword arguments to pass to the task.

        Returns
        -------
        The outputs of the task.
        """
        context = dict(self.context or {}, **(context or {}))
        self.param.update(status="running", running=True)
        await asyncio.sleep(0.1)  # Allow _running watcher to insert progress bar before execution starts
        try:
            if not self._prepared:
                await self.prepare(context)
            views, out_context = await self._execute(context, **kwargs)
        except asyncio.CancelledError:
            self.status = "cancelled"
            raise
        except Exception:
            self.status = "error"
            raise
        finally:
            if self.status not in ("error", "cancelled"):
                self.status = "success"
            self.running = False
        self.out_context = out_context
        return views, out_context

    async def prepare(self, context: TContext):
        self._prepared = True

    def reset(self):
        """Resets the view, removing generated outputs."""
        self.status = "idle"
        self._view[:] = []
        self.out_context.clear()


class TaskGroup(Task):

    _current = param.Integer(default=0)

    _tasks = param.List(item_type=Task)

    level = 3

    __abstract = True

    def __init__(self, *tasks, **params):
        if not tasks:
            tasks = params.pop('tasks', [])
        else:
            tasks = list(tasks)
        self._task_watchers = {}
        _tasks = []
        current = 0
        for i, task in enumerate(tasks):
            if isinstance(task, FunctionType):
                task = FunctionTool(task)
            if isinstance(task, Actor) and not issubclass(Actor, self.param._tasks.item_type):
                task = ActorTask(task)
            if isinstance(task, Task):
                task.parent = self
                self._task_watchers[task] = task.param.watch(
                    self._sync_context, 'out_context'
                )
            if current == i and task.status == "success":
                current = i+1
            _tasks.append(task)
        if "status" not in params and current == len(tasks):
            params["status"] = "success"
        super().__init__(_tasks=_tasks, _current=current, **params)
        self._watchers = {}
        self._init_view()
        self._init_views()
        self._populate_view()

    def _init_views(self):
        views = self.param._header.rx()
        for task in self:
            views += task.param.views.rx()
        self.views = views

    async def _sync_context(self, event: param.parameterized.Event):
        task = event.obj
        if task not in self:
            if task in self._task_watchers:
                watcher = self._task_watchers.pop(task)
                task.param.unwatch(watcher)
            return
        index = self._tasks.index(task)+1
        if index > self._current or self.running:
            # No need to invalidate if the task hasn't been executed
            return
        changed = {k for k, v in event.new.items() if k in event.old and not is_equal(event.old.get(k), v)}
        if changed:
            self.invalidate(changed, start=index)
            root = self
            while root.parent is not None:
                root = root.parent
            if not (root is self and index >= len(self)):
                await root.execute()

    def __len__(self) -> int:
        return len(self._tasks)

    def __iter__(self) -> Iterator[Task]:
        return iter(self._tasks)

    def __getitem__(self, index) -> Task:
        return self._tasks[index]

    def __contains__(self, value: Any):
        return value in self._tasks

    def __repr__(self):
        params = []
        if self.title:
            params.append(f"title='{self.title}'")
        tasks = [f"\n    {task!r}" for task in self]
        return f"{self.__class__.__name__}({', '.join(params)}{''.join(tasks)})"

    def _populate_view(self):
        self._view[:] = self._header + self._tasks

    async def _run_task(
        self, i: int, task: Self | Actor, context: TContext, **kwargs
    ) -> tuple[list[Any], TContext]:
        if task.status == "success":
            return task.views, task.out_context
        await asyncio.sleep(0.01)
        messages = self._render_message_history(context)
        subcontext = self._get_context(i, context, task)
        task_history = messages + task.history
        with task.param.update(
            interface=self.interface,
            llm=task.llm or self.llm,
            steps_layout=self.steps_layout,
            running=True,
            history=task_history
        ):
            outputs, out_context = await task.execute(subcontext, **kwargs)
        if isinstance(task, ContextProvider):
            unprovided = [
                p for p in task.output_schema.__required_keys__
                if p not in out_context
            ]
            if unprovided:
                raise RuntimeError(f"{task.__class.__name__} failed to provide declared context.")
        return outputs, out_context

    def _render_tasks(self) -> list[tuple[str, Viewable]]:
        tasks = []
        for task in self:
            task_type = type(task).__name__
            tasks.append((
                f'{task_type}: {task.title}',
                task.editor(show_title=False)
            ))
        return tasks

    def _get_context(
        self, i: int, context: TContext | None, task: Task | ContextProvider
    ) -> TContext | None:
        contexts = ([self.context] if self.context else []) + ([context] if context else [])
        contexts += [task.out_context for task in self[:i]]
        if isinstance(task, ContextProvider):
            return merge_contexts(task.input_schema, contexts)
        elif isinstance(task, TaskGroup):
            # Accumulate contexts requested by subtasks and merge based
            subcontexts = []
            for subtask in task:
                subtask_context = self._get_context(i, context, subtask)
                if subtask_context is not None:
                    subcontexts.append(subtask_context)
            return merge_contexts(LWW, subcontexts)
        else:
            raise TypeError("Abstract Task does not implement _get_context.")

    async def _execute(self, context: TContext, **kwargs):
        """
        Executes the tasks.

        Arguments
        ---------
        context: TContext
            The context given to the task
        **kwargs: dict
            Additional keyword arguments to pass to the tasks.
        """
        if self.title and not self._header:
            self._header = views = [self._title]

        views = list(self._header)
        self.status = "running"
        for i, task in enumerate(self):
            new = []
            try:
                new, new_context = await self._run_task(i, task, context, **kwargs)
            except asyncio.CancelledError:
                self.status = "cancelled"
                raise
            except MissingContextError:
                # Re-raise MissingContextError to allow retry logic at Plan level
                raise
            except Exception as e:
                tb.print_exception(e)
                self.status = "error"
                new_context = {"__error__": str(e), "__error_type__": type(e)}
                task.out_context = new_context
                if self.abort_on_error:
                    if self.parent is not None:
                        raise e
                    break
                else:
                    continue
            else:
                if task.status == "error":
                    self.status = "error"
                    if self.abort_on_error:
                        break
                views += new
            finally:
                self._current = i + (0 if task.status in ("error", "cancelled") else 1)
        if self.status not in ("error", "cancelled"):
            self.status = "success"
        contexts = [self.context] if self.context else []
        contexts += [task.out_context for task in self]
        return views, merge_contexts(LWW, contexts)

    def append(self, task: Task | Actor):
        """
        Appends a task to the collection.

        Arguments
        ----------
        task: Task | Actor
            The task to append.
        """
        if not isinstance(task, Task):
            task = ActorTask(task)
        task.parent = self
        self._tasks.append(task)
        self._populate_view()
        self._init_views()

    def remove(self, task: Task | list[Task]):
        tasks = task if isinstance(task, list) else [task]
        for t in tasks:
            self._tasks.remove(t)
        self._populate_view()
        self._init_views()
        self._current = min(self._current, len(self))

    def cleanup(self):
        for task, watcher in self._task_watchers.items():
            task.param.unwatch(watcher)
        super().cleanup()

    def editor(self, show_title=True):
        """
        Returns the editor for the tasks.

        Arguments
        ----------
        show_title: bool
            Whether to show the title of the tasks.

        Returns
        -------
        The editor for the tasks.
        """
        return Column(
            *self._render_controls(),
            *((
                Divider(sizing_mode="stretch_width", margin=(10, 0)),
                Accordion(
                    *self._render_tasks(), margin=(10, 0, 10, 0), title_variant="h4",
                    toggle=True, sizing_mode="stretch_width"
                ),
              ) if self._tasks else ()
            )
        )

    def insert(self, index, task: Task | Actor):
        """
        Inserts a task at the given index.

        Arguments
        ----------
        index: int
            The index to insert the task at.
        task: Task | Actor
            The task to insert.
        """
        if not isinstance(task, Task):
            task = ActorTask(task)
        task.parent = self
        self._tasks.insert(index, task)
        self._populate_view()
        self._init_views()

    def invalidate(
        self, keys: Iterable[str], start: int = 0, propagate: bool = True
    ) -> tuple[list[Task], set[str]]:
        """
        Invalidates tasks and propagates context dependencies within a TaskGroup.

        Parameters
        ----------
        keys : Iterable[str]
            A set of context keys that have been modified or invalidated by the user.
            These represent outputs whose dependent tasks should be re-evaluated.
        start : int
            Index of the task to start invalidating.
        propagate: bool
            Whether to propagate the invalidation to the parent task group.

        Returns
        -------
        tuple[bool, set[str]]
            A tuple ``(invalidated, keys)`` where:
            - ``invalidated`` is ``True`` if any tasks in this group (or nested groups)
                were marked invalid due to overlapping input dependencies.
            - ``keys`` is the full, cumulative set of invalidated context keys after
                propagating dependencies through all affected tasks.

        Notes
        -----
        - If a task's input keys intersect with the provided invalidation keys,
        that task is considered stale and will be rerun.
        - Nested TaskGroups are traversed recursively, and their invalidations
        propagate upward to the parent group.
        """
        if propagate and self.parent is not None and self in self.parent:
            parent_idx = self.parent._tasks.index(self)
            if start >= len(self):
                # If the last task is being invalidated,
                # only subsequent tasks on the parent
                # have to be invalidated
                parent_idx += 1
            self.parent.invalidate(keys, start=parent_idx)
            return

        if start == 0:
            self._header = []

        keys = set(keys)
        invalidated = []
        for i, task in enumerate(self):
            if i < start:
                continue
            subtask_invalidated, subtask_keys = task.invalidate(keys, propagate=False)
            if subtask_invalidated:
                invalidated.append(i)
                keys |= subtask_keys

        if invalidated:
            self.status = "idle"
            self._current = max(min(invalidated), 0)
        return [self[i] for i in invalidated], keys

    def merge(self, other: TaskGroup):
        """
        Merges another task group into the current task group.

        Parameters
        ---------
        other: TaskGroup
            The other task group to merge with.

        Returns
        -------
        self: TaskGroup
            The current task group.
        """
        for task in other:
            other.parent = self
            self._tasks.append(task)
        self._view[:] = list(self._view) + list(other._view)
        self.context = merge_contexts(LWW, [self.context, other.context])
        self.out_context = merge_contexts(LWW, [self.context, self.out_context])
        self.history += [h for h in other.history if h not in self.history]
        self._init_views()
        return self

    async def prepare(self, context: TContext):
        for task in self:
            await task.prepare(context)
        self._prepared = True

    def reset(self, start: int = 0):
        """
        Resets the view, removing generated outputs.
        """
        self.status = "idle"
        self._current = start
        with hold():
            self._header = []
            self._view.clear()
            for task in self[start:]:
                if isinstance(task, Task):
                    task.reset()
            self._populate_view()

    def validate(
        self,
        context: TContext | None = None,
        available_types: dict[str, Any] | None = None,
        path: str | None = None,
        raise_on_error: bool = True
    ):
        """
        Validate the task group and its subtasks.

        Parameters
        ----------
        context : TContext | None, optional
            The context to validate against, by default None
        available_types : dict[str, Any] | None, optional
            Dictionary of available types for validation, by default None
        path : str | None, optional
            Path to the current task group for error reporting, by default None
        raise_on_error : bool, optional
            Whether to raise an error if validation issues are found, by default True

        Returns
        -------
        tuple[list[ValidationIssue], dict[str, Any]]
            A tuple containing:
            - List of validation issues found
            - Dictionary of output types from all tasks
        """
        cur_path = path or self.name
        issues: list[ValidationIssue] = validate_taskgroup_exclusions(self, path=cur_path)
        value_ctx = dict((self.context or {}), **(context or {}))
        types_out: dict[str, Any] = dict(available_types or {})
        for idx, t in enumerate(self):
            subpath = f"{cur_path}[{idx}] -> {t.name}"
            sub_issues, sub_types = t.validate(
                value_ctx,
                available_types=types_out,
                path=subpath,
            )
            issues.extend(sub_issues)
            types_out.update(sub_types)
        if path is None and issues and raise_on_error:
            raise ContextError(issues)
        return issues, types_out


class Section(TaskGroup):
    """
    A `Section` is a `TaskGroup` representing a sequence of related tasks.
    """

    level = 2

    def __init__(self, *tasks, **params):
        self._watchers = {}
        self._placeholder = None
        self._task_previews = None
        super().__init__(*tasks, **params)
        self._update_placeholder()

    def __repr__(self) -> str:
        params = []
        if self.title:
            params.append(f"title='{self.title}'")
        tasks = [f"\n    {task!r}" for task in self]
        return f"{self.__class__.__name__}({', '.join(params)}{''.join(tasks)})"

    def _render_controls(self):
        return [
            TextInput.from_param(
                self.param.title, sizing_mode="stretch_width", margin=(10, 0)
            )
        ]

    def _init_view(self):
        self._dialog = Dialog(
            self.editor(),
            show_close_button=True,
            close_on_click=True,
            title=f'Section Configuration: {self.title}',
        )
        self._settings = IconButton(
            icon='settings', on_click=self._open_settings, size="small", color="default"
        )
        self._placeholder = Typography(
            "", variant="body2", margin=(10, 10),
            sx={"color": "text.secondary"}
        )
        self._task_previews = Column(
            sizing_mode='stretch_width',
            styles={'min-height': 'unset'},
            height_policy='fit',
            visible=False,
        )
        self._view = Column(sizing_mode='stretch_width', styles={'min-height': 'unset'}, height_policy='fit')
        self._container = Column(
            Row(
                self._settings,
                styles={'position': 'absolute', 'top': '-57.5px', 'right': '20px'}
            ),
            self._dialog,
            self._view,
            sizing_mode='stretch_width',
            styles={'min-height': 'unset'},
            height_policy='fit'
        )

    def _open_settings(self, event):
        self._dialog.open = True

    @param.depends('status', '_tasks', 'views', watch=True)
    def _update_placeholder(self):
        """Update placeholder text based on execution status."""
        if self._placeholder is None:
            return
        has_outputs = self.status != "idle" or bool(self.views)
        if not has_outputs:
            n = len(self._tasks)
            self._placeholder.object = f"{n} ready to launch!"
            self._placeholder.visible = True
            # Show task title previews
            if self._task_previews is not None:
                previews = []
                for task in self._tasks:
                    if task.title:
                        indent = max(0, task.level - self.level) * 16
                        previews.append(Typography(
                            task.title,
                            variant="body2",
                            margin=(2, 10, 2, 10 + indent),
                            sx={"color": "text.disabled"},
                        ))
                self._task_previews[:] = previews
                self._task_previews.visible = bool(previews)
        else:
            self._placeholder.visible = False
            if self._task_previews is not None:
                self._task_previews.visible = False

    def _populate_view(self):
        placeholders = [self._placeholder]
        if self._task_previews is not None:
            placeholders.append(self._task_previews)
        self._view[:] = self._header + placeholders + [self._task_view(task) for task in self._tasks]

    def _task_view(self, task):
        """
        Give every task its own export checkbox, so a single chart can be
        dropped without discarding the whole section it came from. The report
        only draws headers for its top level sections, so without this nothing
        inside one could be selected.

        A nested section gets a heading too, unless it takes its parent's title
        (a section wrapping a single plan does), which would repeat the heading
        the report already shows.
        """
        if isinstance(task, Section):
            if task.title == self.title:
                return task
            return Column(
                _export_header(task, task, variant="h4"),
                task,
                sizing_mode="stretch_width",
                styles={'min-height': 'unset'},
                height_policy='fit',
            )
        return Row(
            _export_checkbox(task, task, align="start"),
            task,
            sizing_mode="stretch_width",
            styles={'min-height': 'unset'},
            height_policy='fit',
        )

    async def _run_task(self, i: int, task: Task | Actor, context: TContext | None, **kwargs) -> list[Any]:
        if context is not None:
            instructions = "\n".join(
                f"{i+1}. {task.instruction}" if hasattr(task, 'instruction') else f"{i+1}. <no instruction>"
                for i, task in enumerate(self)
            )
            context['reasoning'] = f"{self.title}\n\n{instructions}"
        return await super()._run_task(i, task, context, **kwargs)

    @param.depends('running', watch=True)
    async def _running(self):
        await asyncio.sleep(0.05)
        if not self.running:
            return
        # Start with indeterminate, switch to determinate after first task
        loader = Progress(
            variant='indeterminate',
            sizing_mode='stretch_width',
            margin=(0, 0, 10, 0)
        )
        self._view.insert(0, loader)

        # Switch to determinate mode once first task completes
        while self._current == 0 and self.running:
            await asyncio.sleep(0.05)

        if self.running and self._current > 0:
            loader.variant = 'determinate'
            progress_value = self.param._current.rx.pipe(lambda x: (x / len(self) * 100) if len(self) > 0 else 0)
            loader.value = progress_value

        while self.running:
            await asyncio.sleep(0.05)
        self._view.remove(loader)


class Report(TaskGroup):
    """
    A `Report` is a `TaskGroup` consisting of a sequence of `Section` objects.

    The `Report` UI renders buttons to execute, clear, export and configure the
    Report.
    """

    auto_execute = param.Boolean(default=False, doc="""
        If True, automatically execute the report on initialization.""")

    _active_task = param.ClassSelector(class_=asyncio.Task, default=None, allow_None=True)

    _tasks = param.List(item_type=Section)

    level = 1

    # The Story tab is appended after the Report tab once a story exists.
    _STORY_TAB = 1

    _STORY_PRESETS = [
        ("Executive summary", "Write a concise executive summary for decision-makers, leading with the key takeaways."),
        ("Technical deep-dive", "Write a detailed technical analysis that explains the methods and the data behind each chart."),
        ("Highlights only", "Keep it brief: just the headline finding for each chart and table."),
    ]

    def __init__(self, *tasks, **params):
        if not tasks:
            tasks = params.pop('tasks', [])
        else:
            tasks = list(tasks)
        super().__init__(*tasks, **params)
        pn.state.execute(partial(self.prepare, self.context))
        if self.auto_execute:
            pn.state.execute(self.execute)

    @classmethod
    def from_views(cls, views: list, title: str | None = None) -> Report:
        """Assemble an exportable Report from prebuilt views without executing tasks.

        Builds a task-less report whose export state is populated directly from
        already-rendered views, so `to_html` and `to_notebook` can produce a
        downloadable report without running an agent. The execute path is
        untouched; only `views`, the `_view` accordion and `status` are set, and
        the empty task list keeps the export guards satisfied.

        Parameters
        ----------
        views : list
            The prebuilt viewable outputs to include, in order.
        title : str, optional
            The report title, used for the exported document.
        """
        report = cls(title=title or "")
        report._view[:] = [
            (view.title if "title" in view.param else "", view) for view in views
        ]
        report.views = list(views)
        report.status = "success"
        return report

    def _init_view(self):
        self._section_headers = {}
        self._story_title = ""
        self._story_blocks = []
        self._story_versions = []
        self._story_version = 0
        self._story_outline = []
        self._header_title = Typography(
            self.param.title, variant="h1", margin=(0, 0, 0, 10)
        )
        self._view = Accordion(
            sizing_mode="stretch_width", min_height=0, margin=(0, 5, 15, 5), toggle=True,
            sx={
                "& .MuiAccordionDetails-root": {
                    "p": "0 calc(2 * var(--mui-spacing)) 1em !important",
                    "overflowX": "auto"
                }
            }
        )
        # The story lives in its own tab so the section accordion (and its
        # checkboxes) is never disturbed, and the two are told apart at a glance
        # rather than by swapping one view for the other. A headerless Card gives
        # it the same white pane as the section cards.
        self._story_column = Card(
            sizing_mode="stretch_width", margin=(0, 5, 15, 5),
            collapsible=False, hide_header=True,
        )
        # The Story tab is added only once a story exists.
        self._tabs = Tabs(("Report", self._view), sizing_mode="stretch_width")
        self._run = IconButton(
            icon="play_arrow", on_click=self._execute_event, margin=0, size="large",
            description="Execute Report", loading=self.param.running,
            visible=self.param._active_task.rx.is_(None),
        )
        self._stop = IconButton(
            icon="stop", on_click=self._handle_cancel, margin=0, size="large",
            description="Stop Report", color="error",
            visible=self.param._active_task.rx.is_not(None),
        )
        self._clear = IconButton(
            icon="clear", on_click=lambda _: self.reset(), margin=0, size="large",
            description="Clear outputs", visible=False
        )
        self._collapse = IconButton(
            styles={"margin-left": "auto"}, on_click=self._expand_all, icon="unfold_less",
            size="large", color="default", margin=(0, 0, 10, 0),
            description="Collapse/Expand Sections", visible=False
        )
        self._settings = IconButton(
            icon="settings", on_click=self._open_settings, size="large", color="default",
            margin=0, description="Configure Report", visible=False
        )
        self._annotate = IconButton(
            icon="auto_stories", on_click=self._open_story_dialog, size="large",
            color="default", margin=0, visible=False,
            description="Annotate the report with an AI-written story",
        )
        self._arrange = IconButton(
            icon="reorder", on_click=self._open_arrange_dialog, size="large",
            color="default", margin=0, visible=False,
            description="Arrange the report (reorder sections and add headings)",
        )
        self._export = MenuButton(
            label="", icon="get_app", variant="text", color="default",
            margin=0, size="large", visible=False,
            description="Export Report",
            items=[
                {"label": "Notebook (.ipynb)", "format": "ipynb", "icon": "description"},
                {"label": "HTML (.html)", "format": "html", "icon": "language"},
            ],
            on_click=lambda _: self._download._transfer(),
            icon_size="36px",
            sx={
                "& .MuiButton-endIcon": {"display": "none"},
                "& .MuiButton-startIcon": {"margin": 0},
                "& .MuiIcon-root": {"color": "var(--mui-palette-action-active)"},
                "minWidth": "unset",
                "width": "60px",
                "height": "60px",
                "borderRadius": "50%",
                "padding": 0,
            },
        )
        self._download = FileDownload(
            auto=True,
            callback=param.bind(self._export_report, self._export),
            filename=f"{self.title or 'Report'}.ipynb",
            visible=False,
        )
        self._export.attached.append(self._download)
        self._dialog = Dialog(
            TextInput.from_param(self.param.title, margin=(10, 0, 0, 0), sizing_mode="stretch_width"),
            show_close_button=True,
            close_on_click=True,
            title=f"Report Settings: {self.title}",
        )
        self._outline_editor = pn.widgets.JSONEditor(
            mode="tree", sizing_mode="stretch_width", height=400,
        )
        self._outline_editor.param.watch(self._on_outline_change, "value")
        self._outline_apply = Button(
            label="Apply", variant="contained", on_click=self._apply_outline,
        )
        self._outline_dialog = Dialog(
            self._outline_editor,
            Row(self._outline_apply, align="end", margin=(10, 0, 0, 0), sizing_mode="stretch_width"),
            show_close_button=True,
            title="Arrange Report",
            width_option="md",
        )
        self._story_guidance = TextAreaInput(
            placeholder="Guide the story, e.g. focus on seasonal trends (optional)",
            sizing_mode="stretch_width", rows=3, margin=(10, 0, 0, 0),
        )
        self._story_presets = Row(
            *[
                Button(
                    label=label, variant="outlined", size="small", color="default",
                    on_click=partial(self._apply_story_preset, text=text),
                )
                for label, text in self._STORY_PRESETS
            ],
            sizing_mode="stretch_width",
        )
        self._story_generate = Button(
            label="Generate", variant="contained", icon="auto_stories",
            on_click=self._generate_story,
        )
        self._story_dialog = Dialog(
            Typography("Pick a tone or write your own guidance, then generate the story.", variant="body2"),
            self._story_presets,
            self._story_guidance,
            Row(self._story_generate, align="end", margin=(10, 0, 0, 0), sizing_mode="stretch_width"),
            show_close_button=True,
            title="Annotate Report",
            width_option="sm",
        )
        # Rewriting a single paragraph with the LLM.
        self._edit_index = None
        self._edit_instruction = TextAreaInput(
            placeholder="How should this paragraph change? e.g. make it shorter and lead with the number",
            sizing_mode="stretch_width", rows=3, margin=(10, 0, 0, 0),
        )
        self._edit_apply = Button(
            label="Rewrite", variant="contained", icon="auto_fix_high",
            on_click=self._rewrite_prose,
        )
        self._edit_dialog = Dialog(
            self._edit_instruction,
            Row(self._edit_apply, align="end", margin=(10, 0, 0, 0), sizing_mode="stretch_width"),
            show_close_button=True,
            title="Edit paragraph with AI",
            width_option="sm",
        )
        self._menu = Row(
            self._header_title,
            self._run,
            self._stop,
            self._clear,
            self._collapse,
            self._annotate,
            self._arrange,
            self._export,
            self._settings,
            sizing_mode="stretch_width"
        )
        self._dial = SpeedDial(
            items=[
                {"label": "Execute Report", "icon": "play_arrow"},
                {"label": "Stop Report", "icon": "stop"},
                {"label": "Clear Report", "icon": "clear"},
                {"label": "Annotate Report", "icon": "auto_stories"},
                {"label": "Arrange Report", "icon": "reorder"},
                {"label": "Export as Notebook", "icon": "description", "format": "ipynb"},
                {"label": "Export as HTML", "icon": "language", "format": "html"},
                {"label": "Configure Report", "icon": "settings"}
            ],
            color="default",
            direction="down",
            icon="more_vert",
            size="small",
            styles={"margin": "10px 10px 10px auto"},
            on_click=self._trigger_event,
            sx={"& .MuiFab-root": {"boxShadow": "var(--mui-shadows-2)"}}
        )
        self._collapsed_menu = Row(
            self._header_title,
            self._dial,
            sizing_mode="stretch_width"
        )
        self._switcher = BreakpointSwitcher(
            media_query='(min-width: 800px)',
            small=self._collapsed_menu,
            large=self._menu,
            sizing_mode="stretch_width"
        )
        self._export_hint = Typography(
            "Untick a chart, table or note to leave it out of the exported report.",
            variant="body2", margin=(0, 10, 10, 10),
            sx={"color": "text.secondary"},
            visible=self.param.status.rx().rx.in_(("success", "error", "cancelled")),
        )
        self._container = Column(
            self._export_hint,
            self._tabs,
            self._dialog,
            self._outline_dialog,
            self._story_dialog,
            self._edit_dialog,
            margin=(0, 0, 0, 5),
            sizing_mode="stretch_both",
            height_policy='fit',
        )
        self._update_run_state()
        self._update_icon_visibility()

    async def _trigger_event(self, item: dict):
        icon = item["icon"]
        if icon == "play_arrow":
            if self._active_task is not None and not self._active_task.done():
                self._handle_cancel()
            else:
                await self._execute_event()
        elif icon == "stop":
            self._handle_cancel()
        elif icon == "clear":
            self.reset()
        elif icon == "auto_stories":
            self._open_story_dialog()
        elif icon == "reorder":
            self._open_arrange_dialog()
        elif icon in ("description", "language"):
            fmt = item.get("format", "ipynb")
            self._export.value = {"format": fmt}
            self._download._transfer()
        elif icon == "settings":
            self._open_settings()

    @param.depends('_current', '_tasks', watch=True)
    def _update_run_state(self):
        # Play button is always enabled - users can re-run after changing settings
        pass

    @param.depends('status', 'views', watch=True)
    def _update_icon_visibility(self):
        """Show/hide icons based on whether report has outputs."""
        has_outputs = self.status in ("success", "error", "cancelled") or bool(self.views)
        self._clear.visible = has_outputs
        self._collapse.visible = has_outputs
        self._annotate.visible = has_outputs
        self._annotate.disabled = self.llm is None
        self._arrange.visible = has_outputs
        self._export.visible = has_outputs
        self._settings.visible = has_outputs
        # Only animate play button when no outputs
        if has_outputs:
            self._run.sx = {}
        else:
            self._run.sx = {
                "animation": "pulse 1s ease-in-out 2",
                "@keyframes pulse": {
                    "0%, 100%": {"transform": "translateX(0)"},
                    "50%": {"transform": "translateX(7px)"},
                },
            }

    async def _execute_event(self, event=None):
        if self._active_task is not None and not self._active_task.done():
            # Already running; the stop button handles cancellation
            return
        # A fresh run invalidates any previously generated story.
        self._discard_story()
        await asyncio.sleep(0.01)  # yield the event loop to allow button loading state to update
        task = asyncio.create_task(self.execute())
        self._active_task = task
        task.add_done_callback(self._on_execute_done)

    def _on_execute_done(self, task):
        """Clear the active task reference so UI controls flip back to idle."""
        if task is not self._active_task:
            return
        self._active_task = None

    def _handle_cancel(self, event=None):
        """Cancel the in-flight report execution, if any."""
        if self._active_task is not None and not self._active_task.done():
            self._active_task.cancel()

    @property
    def _export_views(self):
        # Task-less reports (e.g. Report.from_views) populate ``views`` directly.
        if not len(self):
            return self.views
        views = list(self._header)
        # When the story view is shown, export the blog-post flow: the story
        # title, then prose interleaved with the charts and tables it discusses.
        if self._show_story and self._story_blocks:
            views.append(Typography(self._story_title, variant="h2"))
            views += [
                Markdown(obj) if kind == "prose" else obj
                for kind, obj in self._story_blocks
            ]
            return views
        if self._story_outline:
            for kind, value, level in self._iter_arrangement():
                if kind == "heading":
                    views.append(Typography(value, variant=f"h{level}"))
                else:
                    self._append_section_views(views, value)
        else:
            for section in self:
                self._append_section_views(views, section)
        return views

    def _append_section_views(self, views, section):
        if not section.include_in_export:
            return
        views += self._selected_views(section)

    def _selected_views(self, group, include_header=True):
        """
        The views of a task group, skipping sections discarded from the export.
        Walks the tasks rather than reading ``group.views`` so that a nested
        section's selection is honoured, not just a top level one's.
        """
        views = list(group._header) if include_header else []
        for task in group:
            if not task.include_in_export:
                continue
            views += self._selected_views(task) if isinstance(task, TaskGroup) else list(task.views)
        return views

    def _section_by_title(self, title):
        for section in self:
            if section.title == title:
                return section
        return None

    def _build_default_outline(self):
        """Seed the arrangement outline from the currently selected sections."""
        return [{"section": section.title} for section in self if section.include_in_export]

    def _export_view(self):
        # Task-less reports (e.g. Report.from_views) populate ``_view`` directly.
        if not len(self):
            return self._view
        # When the story view is shown, save the same blog-post flow shown live:
        # prose interleaved with the charts and tables, matching the notebook.
        if self._show_story and self._story_blocks:
            return Column(*self._story_flow(), sizing_mode="stretch_width", margin=(0, 5, 15, 5))
        # Build each card from the section's selected views rather than the
        # section itself, so a discarded nested section is left out of the HTML
        # too. The card header already shows the title, hence no heading.
        cards = []
        if self._story_outline:
            # Follow the arranged outline so HTML matches the notebook order.
            for kind, value, _ in self._iter_arrangement():
                if kind == "heading":
                    cards.append((value, Markdown(f"### {value}")))
                else:
                    cards.append((
                        value.title,
                        Column(*self._selected_views(value, include_header=False), sizing_mode="stretch_width"),
                    ))
        else:
            cards += [
                (
                    section.title,
                    Column(*self._selected_views(section, include_header=False), sizing_mode="stretch_width"),
                )
                for section in self if section.include_in_export
            ]
        return Accordion(
            *cards,
            active=list(range(len(cards))),
            sizing_mode="stretch_width",
            min_height=0,
            margin=(0, 5, 15, 5),
            sx=self._view.sx,
        )

    def to_notebook(self):
        """
        Returns the notebook representation of the report.
        """
        if len(self) and not self.status == "success":
            raise RuntimeError(
                "Report has not been executed, run report before exporting to_notebook."
            )
        cells, extensions = [], ['tabulator']
        pending_headers = []
        for out in self._export_views:
            cell = ext = None
            if isinstance(out, Typography):
                # Buffer headers; only emit them if followed by exportable content
                level = int(out.variant[1:]) if out.variant and out.variant.startswith('h') else 0
                prefix = f"{'#'*level} " if level else ''
                pending_headers.append(make_md_cell(f"{prefix}{out.object}"))
                continue
            elif isinstance(out, Markdown):
                cell = make_md_cell(out.object)
            elif isinstance(out, LumenEditor):
                cell, ext = format_output(out)
            elif isinstance(out, str):
                cell = make_md_cell(out)
            elif isinstance(out, ChatMessage):
                obj = out.object
                if isinstance(obj, str):
                    cell = make_md_cell(obj)
                elif isinstance(obj, Markdown):
                    cell = make_md_cell(obj.object)
            # Skip non-LumenEditor Viewables (not meaningfully exportable)

            if cell is None:
                continue
            # Flush buffered headers before the content cell
            cells.extend(pending_headers)
            pending_headers.clear()
            cells.append(cell)
            if ext and ext not in extensions:
                extensions.append(ext)
        cells = make_preamble("", extensions=extensions) + cells
        return write_notebook(cells)

    def to_html(self):
        """
        Returns the HTML representation of the report.
        """
        if len(self) and self.status != "success":
            raise RuntimeError(
                "Report has not been executed, run report before exporting to html."
            )
        buf = io.StringIO()
        self._export_view().save(buf, title=self.title or "Report")
        return buf.getvalue()

    async def _export_report(self, item=None):
        if len(self) and self.status not in ("success", "cancelled", "error"):
            await self.execute()
        fmt = item.get("format", "ipynb") if isinstance(item, dict) else "ipynb"
        title = self.title or "Report"
        ext = "html" if fmt == "html" else "ipynb"
        self._download.filename = f"{title}.{ext}"
        if fmt == "html":
            return io.StringIO(self.to_html())
        return io.StringIO(self.to_notebook())

    def _expand_all(self, event=None):
        if self._collapse.icon == "unfold_less":
            self._view.active = []
            self._collapse.icon = "expand"
        else:
            self._view.active = list(range(len(self._view)))
            self._collapse.icon = "unfold_less"

    def _open_settings(self, event=None):
        self._dialog.open = True

    def _open_arrange_dialog(self, event=None):
        # Seed from the current arrangement, or the default section order.
        self._outline_editor.value = self._story_outline or self._build_default_outline()
        self._outline_dialog.open = True

    def _on_outline_change(self, event):
        self._story_outline = event.new or []
        self._populate_view()

    def _apply_outline(self, event=None):
        # Read the editor's current value explicitly and apply the arrangement
        # to both the live report and the exports.
        self._story_outline = list(self._outline_editor.value or [])
        self._populate_view()
        self._outline_dialog.open = False

    def _open_story_dialog(self, event=None):
        self._story_dialog.open = True

    def _apply_story_preset(self, event=None, text=""):
        self._story_guidance.value = text

    async def _generate_story(self, event=None):
        guidance = (self._story_guidance.value or "").strip()
        self._story_dialog.open = False
        await self._annotate_report(guidance=guidance)

    def _collect_story_views(self):
        """Charts and tables from the selected sections, in reading order."""
        return [
            view
            for section in self if section.include_in_export
            for view in section.views if isinstance(view, LumenEditor)
        ]

    async def _annotate_report(self, event=None, guidance=""):
        """Write an AI blog-post story over the selected charts/tables and render it."""
        if self.llm is None or not len(self):
            return
        from .agents.story import StoryAgent, build_catalog
        catalog = self._collect_story_views()
        if not catalog:
            return
        self._annotate.loading = True
        self._story_generate.loading = True
        try:
            agent = StoryAgent(llm=self.llm)
            story = await agent.write_story(
                await build_catalog(catalog), guidance=guidance, title=self.title or "",
            )
            self._set_story(story, catalog)
        except Exception:
            tb.print_exc()
        finally:
            self._annotate.loading = False
            self._story_generate.loading = False

    def _set_story(self, story, catalog):
        """Resolve the LLM story into interleaved prose/view blocks as a new version."""
        blocks, used = [], set()
        for block in story.blocks:
            if block.prose and block.prose.strip():
                blocks.append(("prose", block.prose))
            index = block.view
            if index is not None and 1 <= index <= len(catalog) and index not in used:
                used.add(index)
                blocks.append(("view", catalog[index - 1]))
        # Never drop a selected chart/table: append any the model did not place.
        for index, view in enumerate(catalog, start=1):
            if index not in used:
                blocks.append(("view", view))
        # Each story is kept as its own version, so regenerating offers a fresh
        # take without throwing away one the user may have edited by hand.
        self._story_versions.append({"title": story.title or "Story", "blocks": blocks})
        self._select_version(len(self._story_versions) - 1)

    def _select_version(self, index):
        """Show one of the generated versions of the story."""
        self._story_version = index
        version = self._story_versions[index]
        self._story_title = version["title"]
        # The version's own list is used live, so edits stay with that version.
        self._story_blocks = version["blocks"]
        self._render_story()

    def _switch_version(self, event):
        self._select_version(event.new)

    def _rebuild_view(self, editor):
        """An independent copy of a chart/table so the story preview never detaches
        it from its section; data is embedded so the copy stands alone."""
        component = editor.component
        with config.param.update(serializer='csv'):
            spec = component.to_spec()
        return Pipeline.from_spec(spec) if isinstance(component, Pipeline) else View.from_spec(spec)

    def _story_flow(self, editable=False):
        """
        The blog-post flow as renderables: the title, then prose interleaved with
        freshly rebuilt charts and tables. Rebuilding gives each caller its own
        copies so the live view and the exports never share objects. Prose is
        editable on screen and plain Markdown when exported.
        """
        items = []
        if self._story_title:
            heading = Typography(self._story_title, variant="h4", margin=(10, 10, 0, 10))
            if editable and self.llm is not None:
                controls = [heading]
                if len(self._story_versions) > 1:
                    version = Select(
                        options={f"Version {i+1}": i for i in range(len(self._story_versions))},
                        value=self._story_version, width=140, align="center",
                        margin=(10, 10, 0, 0), label="",
                        description="Switch between the generated versions of the story",
                    )
                    version.param.watch(self._switch_version, "value")
                    controls.append(version)
                # Regenerating reopens the guidance popup, so a fresh story can be
                # written with a different angle as a new version.
                controls.append(Button(
                    label="Regenerate", variant="outlined", size="small", color="default",
                    icon="refresh", align="center", margin=(10, 10, 0, 0),
                    description="Write the story again as a new version",
                    on_click=self._open_story_dialog,
                ))
                heading = Row(*controls, align="center", sizing_mode="stretch_width")
            items.append(heading)
        for index, (kind, obj) in enumerate(self._story_blocks):
            if kind != "prose":
                items.append(self._rebuild_view(obj))
            elif editable:
                items.append(self._editable_prose(index, obj))
            else:
                items.append(Markdown(obj, sizing_mode="stretch_width", margin=(5, 10)))
        return items

    def _editable_prose(self, index, text):
        """Prose the user can edit in place, by hand or by asking the LLM."""
        prose = EditableProse(value=text, sizing_mode="stretch_width", margin=(5, 10))
        prose.param.watch(partial(self._update_prose, index), "value")
        edit = IconButton(
            icon="auto_fix_high", size="small", color="default", align="start",
            margin=(5, 0, 0, 0), visible=self.llm is not None,
            description="Rewrite this paragraph with AI",
            on_click=partial(self._open_edit_dialog, index),
        )
        return Row(prose, edit, sizing_mode="stretch_width")

    def _update_prose(self, index, event):
        # Keep the story blocks as the single source of truth so manual edits
        # survive tab switches and flow into every export.
        self._story_blocks[index] = ("prose", event.new)

    def _open_edit_dialog(self, index, event=None):
        self._edit_index = index
        self._edit_instruction.value = ""
        self._edit_dialog.open = True

    async def _rewrite_prose(self, event=None):
        """Ask the LLM to rewrite the paragraph the edit dialog was opened on."""
        instruction = (self._edit_instruction.value or "").strip()
        if self.llm is None or self._edit_index is None or not instruction:
            return
        from .agents.story import StoryAgent, build_catalog
        self._edit_dialog.open = False
        self._edit_apply.loading = True
        try:
            agent = StoryAgent(llm=self.llm)
            edit = await agent.rewrite_prose(
                self._story_blocks[self._edit_index][1],
                instruction,
                await build_catalog(self._collect_story_views()),
            )
            self._story_blocks[self._edit_index] = ("prose", edit.prose)
            self._render_story()
        except Exception:
            tb.print_exc()
        finally:
            self._edit_apply.loading = False

    @property
    def _show_story(self):
        """Whether the story, rather than the report, is the view on screen."""
        return len(self._tabs) > self._STORY_TAB and self._tabs.active == self._STORY_TAB

    def _render_story(self):
        """Build the blog-post flow into the Story tab, then switch to it."""
        self._story_column[:] = self._story_flow(editable=True)
        if len(self._tabs) <= self._STORY_TAB:
            self._tabs.append(("Story", self._story_column))
        self._tabs.active = self._STORY_TAB

    def _discard_story(self):
        """Forget every generated version and drop back to the report tab."""
        self._story_blocks = []
        self._story_title = ""
        self._story_versions = []
        self._story_version = 0
        self._story_column[:] = []
        if len(self._tabs) > self._STORY_TAB:
            self._tabs.pop(self._STORY_TAB)
        # Popping leaves ``active`` pointing at the removed tab.
        self._tabs.active = 0

    def reset(self, start: int = 0):
        # Clearing the report also drops the generated story.
        self._discard_story()
        super().reset(start)

    def _section_header(self, section):
        """Card header with a checkbox to keep/discard the section on export."""
        return _export_header(section, self)

    def _iter_arrangement(self, selected_only=True):
        """
        Yield the arranged outline as ('heading', text, level) or
        ('section', section, None) items, resolving section titles and
        dropping duplicates (and, by default, discarded sections).
        """
        seen = set()
        for block in self._story_outline:
            if "heading" in block:
                yield "heading", block["heading"], block.get("level", 2)
            elif "section" in block:
                section = self._section_by_title(block["section"])
                if section is None or id(section) in seen:
                    continue
                if selected_only and not section.include_in_export:
                    continue
                seen.add(id(section))
                yield "section", section, None

    def _ordered_sections(self):
        """Sections in the arranged outline order (unreferenced ones kept at the end)."""
        if not self._story_outline:
            return list(self)
        ordered = [s for kind, s, _ in self._iter_arrangement(selected_only=False) if kind == "section"]
        seen = {id(section) for section in ordered}
        for section in self:
            if id(section) not in seen:
                ordered.append(section)
        return ordered

    def _populate_view(self):
        headers = {}
        objects = []
        for section in self._ordered_sections():
            header = self._section_headers.get(section) or self._section_header(section)
            headers[section] = header
            objects.append((header, section))
        self._section_headers = headers
        self._view[:] = objects
        has_outputs = self.status in ("success", "error", "cancelled") or bool(self.views)
        if has_outputs:
            self._view.active = list(range(len(objects)))
        else:
            self._view.active = list(range(len(objects))) if objects else []

    async def _run_task(self, i: int, task: Section, context: TContext, **kwargs):
        self._view.active = self._view.active + [i]
        outputs = await super()._run_task(i, task, context, **kwargs)
        return outputs

    def __panel__(self):
        return Container(
            self._switcher,
            self._container,
            align="center",
            sizing_mode="stretch_both",
            stylesheets=[":host > div { overflow-y: auto; }"],
            sx={
                "minWidth": "320px",
                "width": "100%",
                "height": "auto",
                ".mui-light &": { "background-color": "var(--mui-palette-grey-100)"},
                ".mui-dark &": { "background-color": "var(--mui-palette-grey-900)"}
            }
        )


class ExecutableTask(Task, ContextProvider):

    level = 3

    def reset(self):
        super().reset()
        self.views = []

    def invalidate(
        self, keys: Iterable[str], start: int = 0, propagate: bool = True
    ) -> tuple[list[Task], set[str]]:
        """
        Invalidates tasks and propagates context dependencies within a TaskGroup.

        Parameters
        ----------
        keys : Iterable[str]
            A set of context keys that have been modified or invalidated by the user.
            These represent outputs whose dependent tasks should be re-evaluated.
        start : int
            Index of the task to start invalidating.
        propagate: bool
            Whether to propagate the invalidation to the parent task group.

        Returns
        -------
        tuple[bool, set[str]]
            A tuple ``(invalidated, keys)`` where:
            - ``invalidated`` is ``True`` if any tasks in this group (or nested groups)
                were marked invalid due to overlapping input dependencies.
            - ``keys`` is the full, cumulative set of invalidated context keys after
                propagating dependencies through all affected tasks.

        Notes
        -----
        - If a task's input keys intersect with the provided invalidation keys,
        that task is considered stale and will be rerun.
        - Nested TaskGroups are traversed recursively, and their invalidations
        propagate upward to the parent group.
        """
        if propagate and self.parent is not None and self in self.parent:
            parent_idx = self.parent._tasks.index(self)
            if start >= len(self):
                # If the last task is being invalidated,
                # only subsequent tasks on the parent
                # have to be invalidated
                parent_idx += 1
            self.parent.invalidate(keys, start=parent_idx)
            return

        keys = set(keys)
        deps = input_dependency_keys(self.input_schema)
        # If no declared dependencies (empty input_schema), consider it as
        # dependent on all context keys - always invalidate when anything changes.
        # This ensures agents like ChatAgent that have no explicit input_schema
        # are re-run when upstream context changes.
        should_invalidate = (not deps and keys) or (deps & keys)
        if should_invalidate:
            if start == 0:
                # Do no reset if invalidation was called
                # solely to notify parent
                self.reset()
            keys |= set(self.output_schema.__annotations__)
            return [self], keys
        return [], keys

    def validate(
        self,
        context: TContext | None = None,
        available_types: dict[str, Any] | None = None,
        path: str | None = None,
        raise_on_error: bool = True
    ):
        """
        Validate the task group and its subtasks.

        Parameters
        ----------
        context : TContext | None, optional
            The context to validate against, by default None
        available_types : dict[str, Any] | None, optional
            Dictionary of available types for validation, by default None
        path : str | None, optional
            Path to the current task group for error reporting, by default None
        raise_on_error : bool, optional
            Whether to raise an error if validation issues are found, by default True

        Returns
        -------
        tuple[list[ValidationIssue], dict[str, Any]]
            A tuple containing:
            - List of validation issues found
            - Dictionary of output types from all tasks
        """
        subpath = f"{path} -> {self.name}" if path else self.name
        value_ctx = dict((self.context or {}), **(context or {}))
        issues = validate_task_inputs(
            self, value_ctx, available_types, subpath
        )
        types_out = collect_task_outputs(self)
        if path is None and issues and raise_on_error:
            raise ContextError(issues)
        return issues, types_out


class ActorTask(ExecutableTask):
    """
    An `ActorTask` wraps an `Actor` in a way that allows persisting
    the message history, instructions, and context as well as making
    it possible to track its outputs.
    """

    actor = param.ClassSelector(class_=Actor)

    level = 3

    def __init__(self, actor: Actor, **params):
        views = params.get("views", None)
        out_context = params.get("out_context", None)
        super().__init__(actor=actor, **params)
        if views and out_context:
            self._add_outputs(views, out_context)

    @property
    def input_schema(self):
        return self.actor.input_schema

    @property
    def output_schema(self):
        return self.actor.output_schema

    async def _update_spec(self, event: param.parameterized.Event):
        self.out_context = dict(self.out_context, **(await event.obj.render_context()))

    def _add_outputs(self, views: list, context: TContext):
        # Handle Tool specific behaviors
        if isinstance(self.actor, Tool):
            # Handle View/Viewable results regardless of agent type
            rendered = []
            for o in views:
                if not isinstance(o, (View, Viewable)):
                    continue
                if isinstance(o, Viewable):
                    pipeline = None if context is None else context.get('pipeline')
                    o = Panel(object=o, pipeline=pipeline)
                o = LumenEditor(
                    component=o, title=self.title
                )
                message_kwargs = dict(value=o, user=self.actor.name)
                if self.interface:
                    self.interface.stream(**message_kwargs)
                rendered.append(o)
            views = rendered

        # Attach retry controls
        for view in views:
            if not isinstance(view, LumenEditor):
                continue
            view.param.watch(self._update_spec, "spec")

        self.views = self._header + views
        rendered = []
        for view in views:
            out = self._render_output(view)
            if out is not None:
                rendered.append(out)
        self._view.extend(rendered)

    async def _execute(self, context: TContext, **kwargs) -> tuple[list[Any], TContext]:
        views = []
        if self.title and not self._header:
            title = Typography(f"{'#'*self.level} {self.title}", margin=(10, 10, 0, 10))
            views.append(title)
            self.views = self._header = [title]

        messages = self._render_message_history(context)
        subcontext = merge_contexts(self.input_schema, [self.context, context])
        with self.actor.param.update(
            interface=self.interface,
            llm=self.actor.llm or self.llm,
            steps_layout=self.steps_layout
        ):
            try:
                kwargs["step_title"] = self.title
                outputs, out_context = await self.actor.respond(messages, subcontext, **kwargs)
            except MissingContextError:
                # Re-raise MissingContextError to allow retry logic at Plan level
                raise
            except Exception as e:
                self.status = "error"
                raise e
            self._add_outputs(outputs, out_context)
        self.status = "success"
        unprovided = [
            p for p in self.output_schema.__required_keys__
            if p not in out_context
        ]
        if unprovided:
            raise RuntimeError(f"{self.actor.__class__.__name__} failed to provide declared context: {', '.join(unprovided)}.")
        contexts = [self.context, out_context] if self.context else [out_context]
        return outputs, merge_contexts(LWW, contexts)

    def _actor_prompt(self, actor: Actor):
        prompt = Select(
            options=list(actor.prompts), label="Select prompt to modify",
            margin=(10, 0), sizing_mode="stretch_width"
        )
        template = pn.rx(actor.prompts)[prompt]['template']
        block = Select(
            options=template.rx.pipe(get_block_names), label='Select block to modify',
            margin=(10, 0, 10, 10), sizing_mode="stretch_width"
        )

        def update_prompt(prompt, block, event):
            if prompt not in actor.template_overrides:
                actor.template_overrides[prompt] = {}
            actor.template_overrides[prompt][block] = event.new

        def edit_prompt(event):
            source = extract_block_source(template.rx.value, block.value)
            editor = TextAreaInput(
                label=f"Edit {prompt.value} prompt's {block.value} block",
                value=source, sizing_mode='stretch_width', margin=(10, 0), height=300
            )
            cancel = IconButton(
                icon="cancel",
                on_click=lambda _: (layout.remove(edit_layout), actor.template_overrides.pop(prompt.value, {}).pop(block.value, None)),
                styles={'position': 'absolute', 'right': '0px', 'zIndex': "9999"}
            )
            edit_layout = Column(cancel, editor)
            editor.param.watch(partial(update_prompt, prompt.value, block.value), 'value')
            layout.append(edit_layout)

        edit = Button(
            icon="edit_note", icon_size='2em', on_click=edit_prompt, height=54,
            margin=(10, 0, 10, 10)
        )
        layout = Column(Row(prompt, block, edit))
        return layout

    async def prepare(self, context: TContext):
        await self.actor.prepare(context)
        self._prepared = True

    def editor(self, show_title=True):
        """
        Returns the editor for the tasks.

        Arguments
        ----------
        show_title: bool
            Whether to show the title of the tasks.

        Returns
        -------
        The editor for the tasks.
        """
        task_type = type(self.actor).__name__
        if isinstance(self.actor, FunctionTool):
            title, prompt = f"{task_type}: {self.actor.function.__name__}", ''
        else:
            title, prompt = task_type, self._actor_prompt(self.actor)
        return Column(
            *self._render_controls(),
            Divider(sizing_mode="stretch_width", margin=(10, 0)),
            Card(
                prompt, margin=(10, 0, 10, 0), title=title, title_variant="h4",
                sizing_mode="stretch_width"
            )
        )


class Action(ExecutableTask):
    """
    An `Action` implements an execute method that performs some unit of work
    and optionally generates outputs to be rendered.
    """

    render_outputs = param.Boolean(default=True, doc="""
         Whether the outputs should be rendered.""")

    def show(self, **kwargs):
        """Show the Action wrapped in a minimal Report UI."""
        section_title = self.title or self.__class__.__name__
        report = Report(
            Section(self, title=section_title),
            title=section_title,
            auto_execute=True
        )
        return report.show(**kwargs)

    def servable(self, **kwargs):
        """Make the Action servable wrapped in a minimal Report UI."""
        section_title = self.title or self.__class__.__name__
        report = Report(
            Section(self, title=section_title),
            title=section_title,
            auto_execute=True
        )
        return report.servable(**kwargs)

    @final
    async def execute(self, context: TContext | None = None, **kwargs):
        views, out_context = await super().execute(context, **kwargs)
        if self.render_outputs:
            self._view[:] = [self._render_output(out) for out in views]
        if self.title:
            views = [self._title] + views
        self.views = views
        self.status = "success"
        return views, out_context
