name: packages
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+a[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+b[0-9]+'
    - 'v[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  # Dry-run only
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * SUN'

jobs:
  conda_build:
    name: Build Conda Packages
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash -l {0}
    env:
      CHANS_DEV: "-c pyviz/label/dev -c conda-forge"
      MPLBACKEND: "Agg"
      PYCTDEV_SELF_CHANNEL: "pyviz/label/dev"
    steps:
      - uses: actions/checkout@v3
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: 3.7
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: conda setup
        run: |
          conda config --set always_yes True
          conda install -c pyviz/label/dev "pyctdev>=0.5"
          doit ecosystem_setup
      - name: conda build
        run: doit package_build $CHANS_DEV --no-pkg-tests
      - name: conda dev upload
        if: (github.event_name == 'push' && (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        run: doit package_upload --token=${{ secrets.CONDA_UPLOAD_TOKEN }} --label=dev
      - name: conda main upload
        if: (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        run: doit package_upload --token=${{ secrets.CONDA_UPLOAD_TOKEN }} --label=dev --label=main
  pip_build:
    name: Build PyPI Packages
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash -l {0}
    env:
      CHANS_DEV: "-c pyviz/label/dev -c conda-forge"
      PKG_TEST_PYTHON: "--test-python=py37"
      PYTHON_VERSION: "3.7"
      MPLBACKEND: "Agg"
      PPU: ${{ secrets.PPU }}
      PPP: ${{ secrets.PPP }}
      PYPI: "https://upload.pypi.org/legacy/"
      PYCTDEV_SELF_CHANNEL: "pyviz/label/dev"
    steps:
      - uses: actions/checkout@v3
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: conda setup
        run: |
          conda create -n test-environment
          conda activate test-environment
          conda config --remove channels defaults
          conda config --env --remove channels defaults
          conda config --env --append channels pyviz/label/dev --append channels conda-forge
          conda install "python=$PYTHON_VERSION" "pyctdev>=0.5"
      - name: env setup
        run: |
          conda activate test-environment
          doit develop_install -o tests
          doit pip_on_conda
      - name: pip build
        run: |
          conda activate test-environment
          doit ecosystem=pip package_build $PKG_TEST_PYTHON --test-group=all
      - name: pip upload
        if: github.event_name == 'push'
        run: |
          conda activate test-environment
          doit ecosystem=pip package_upload -u $PPU -p $PPP -r $PYPI
